### ISSUE TITLE
Uniswap V3 DEX Volume Missing Optimism

### ISSUE THREAD

**Issue by MSilb7** [DefiLlama/dimension-adapters#345]
Optimism volume is commented out of the Uniswap V3 adapter. Is there a subgraph bug or another issue that needs to be fixed, or can this be added back in? https://github.com/DefiLlama/dimension-adapters/blob/master/protocols/uniswap/index.ts#L22

**Comment by 0xngmi** [comment]
looks like it now its fine and volume is being counted on optimism, i think the issue before was that the subgraph for univ3 started reporting insane inflated numbers on optimism and that's why it got delisted as a temporary measure while uniswap devs were fixing it

btw, we don't really check issues because we have few people contacting us that way, so if in the future you want to contact us feel free to use our discord or dm me directly

![llamafell](https://github.com/DefiLlama/dimension-adapters/assets/80541789/9d5d9bd4-fd2e-469c-8e6c-dc4c126b8be9)
